### ISSUE TITLE
is the generate percentage based on leaves, or on actual trees?

### ISSUE THREAD

**Issue by JustEli** [Huskehhh/HoneyPopulator#3]
Seems like A LOT of bee nests spawn: for my server about every other tree. Not to mention that a lot of trees spawn with several bee nests like here
![image](https://user-images.githubusercontent.com/8517465/71422776-dd62ce00-2684-11ea-8317-dd88bf87b70e.png)

Is it a 5% chance for each bottom of a leaves block? That's what I assume now.

**Comment by Huskehhh** [comment]
Are you using the latest build?

I had an issue with this in prior builds but haven’t been able to replicate since.

The chance is per chunk.

**Comment by JustEli** [comment]
using the latest

**Comment by snurre0** [comment]
I have seen this a few times too, while flying around to test this plugin.
Seems to happen mostly on large oak trees. Is the percent chance pr. log block or something?

For the few trees that are in plains biomes, the spawn rate seems fine though.
But I do see hives generate several in almost every chunk in a flower forest, maybe because there are so many trees there?
In vanilla worldgen(according to the wiki at least), the chance are much higher in a flower forest, because there are a lot more trees there than in a plains biome, so I guess it's a percent chance pr. tree/log.
Is this plugin working the same way? In that case, that might be the reason for multiple generation in the same chunk/tree.

(Long post, I know. Just a few thoughts I'm no developer).
I really like the plugin so far!

**Comment by Huskehhh** [comment]
The plugin works per-chunk. So it should never generate a bee nest on a tree that's in a chunk that has already been processed. That being said, if the large tree for example, spreads over two chunks, it will populate both chunks (bug!)

Something that will cause multiple bee nests is also using HoneyPopulator in a new chunk that Minecraft 1.15 itself generates.

Flower forests are very dense with trees, and yeah, they all get looked over for generation, so they are usually prime spot for bee nests. I will do a bit more refining of the percentage when I get back from holiday, which will hopefully make it a bit more accurate.

**Comment by Huskehhh** [comment]
As I am now unable to reproduce, I'm going to assume this is fixed. If it's not, please re-open the issue! :)
